org: devingen
app: devingen-io
service: kimlik-api

frameworkVersion: '^3.1.1'

provider:
  name: aws
  runtime: go1.x
  environment:
    KIMLIK_API_MONGO_URI: ${param:KIMLIK_API_MONGO_URI}
    KIMLIK_API_JWT_SIGN_KEY: ${param:KIMLIK_API_JWT_SIGN_KEY}
    KIMLIK_API_WEBHOOK_HEADERS: ${param:KIMLIK_API_WEBHOOK_HEADERS}
    KIMLIK_API_WEBHOOK_URL: ${param:KIMLIK_API_WEBHOOK_URL}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:

  register-with-email:
    handler: bin/register-with-email
    events:
      - http:
          path: /{base}/register
          method: post
          cors: true
          request:
            parameters:
              paths:
                base: true

  login-with-email:
    handler: bin/login-with-email
    events:
      - http:
          path: /{base}/login
          method: post
          cors: true
          request:
            parameters:
              paths:
                base: true

  get-session:
    handler: bin/get-session
    events:
      - http:
          path: /{base}/session
          method: get
          cors: true
          request:
            parameters:
              paths:
                base: true

  change-password:
    handler: bin/change-password
    events:
      - http:
          path: /{base}/auth/password
          method: put
          cors: true
          request:
            parameters:
              paths:
                base: true

  find-users:
    handler: bin/find-users
    events:
      - http:
          path: /{base}/users
          method: get
          cors: true
          request:
            parameters:
              paths:
                base: true

  create-api-key:
    handler: bin/create-api-key
    events:
      - http:
          path: /{base}/api-keys
          method: post
          cors: true
          request:
            parameters:
              paths:
                base: true

  find-api-keys:
    handler: bin/find-api-keys
    events:
      - http:
          path: /{base}/api-keys
          method: get
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true

  update-api-key:
    handler: bin/update-api-key
    events:
      - http:
          path: /{base}/api-keys/{id}
          method: put
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true
                id: true

  delete-api-key:
    handler: bin/delete-api-key
    events:
      - http:
          path: /{base}/api-keys/{id}
          method: delete
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true
                id: true

  verify-api-key:
    handler: bin/verify-api-key
    events:
      - http:
          path: /{base}/api-keys/verify
          method: get
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true

  create-saml-config:
    handler: bin/create-saml-config
    events:
      - http:
          path: /{base}/saml-configs
          method: post
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true

  find-saml-configs:
    handler: bin/find-saml-configs
    events:
      - http:
          path: /{base}/saml-configs
          method: get
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true

  update-saml-config:
    handler: bin/update-saml-config
    events:
      - http:
          path: /{base}/saml-configs/{id}
          method: put
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true
                id: true

  delete-saml-config:
    handler: bin/delete-saml-config
    events:
      - http:
          path: /{base}/saml-configs/{id}
          method: delete
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true
                id: true

  build-saml-auth-url:
    handler: bin/build-saml-auth-url
    events:
      - http:
          path: /{base}/saml-configs/{id}/build
          method: post
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true
                id: true

  consume-saml-auth-response:
    handler: bin/consume-saml-auth-response
    events:
      - http:
          path: /{base}/saml-configs/{id}/consume
          method: post
          cors:
            headers: "*"
          request:
            parameters:
              paths:
                base: true
                id: true
